apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: live-migration-shared
spec:
  desiredState:
    interfaces:
      # 1. additional vlan interface to base host interface
      - name: enp4s0u2u1.3876
        description: host NFS access interface with DHCP IP
        type: vlan
        state: up
        
        # Define the parent interface and vlan id
        vlan:
          base-iface: enp4s0u2u1
          id: 3876
          
        # Configure the dynamic IP address for the host
        ipv4:
          enabled: true
          dhcp: true
            
      # 2. ovs bridge definition with ports
      - name: br-lm
        state: up
        type: ovs-bridge
        bridge:
          allow-extra-patch-ports: true
          options:
            stp: false
          port:
            # NAD based configuration ports 
            - name: enp4s0u2u1
            - name: br-lm 
            
    # 3. ovn bridge mappings for localnet
    ovn:
      bridge-mappings:
      - bridge: br-lm
        localnet: ovs-lm
        state: present